name: VeryLobby
version: 1.0
author: Farmeurimmo
main: fr.verymc.main
softdepend: [HolographicDisplays]
commands:
  site:
  discord:
  serveur:
  builder:
  boutique:
  skyblock:
  leavequeues: